services:
  webapp:
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - database
    environment:
      JDBC_URL: jdbc:mysql://database:3306/social_network
      JDBC_USERNAME: social_network_user
      JDBC_PASSWORD: social_network_secret
    volumes:
      - type: bind
        source: ./wait-for-it.sh
        target: /wait-for-it.sh
        read_only: true
    command: ["./wait-for-it.sh", "--timeout=90", "database:3306", "--", "java", "-jar", "app.jar"]

  database:
    image: mysql:8-debian
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: y
      MYSQL_DATABASE: social_network
      MYSQL_USER: social_network_user
      MYSQL_PASSWORD: social_network_secret
    command: ["--secure-file-priv=/docker-entrypoint-initdb.d"]
    volumes:
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/1.init.sql
        read_only: true
      - type: bind
        source: ./fill.sql
        target: /docker-entrypoint-initdb.d/2.fill.sql
        read_only: true
      - type: bind
        source: ./generated_users.csv
        target: /docker-entrypoint-initdb.d/generated_users.csv
        read_only: true
      - type: bind
        source: ./generated_interests.csv
        target: /docker-entrypoint-initdb.d/generated_interests.csv
        read_only: true
